samples_per_pixel: 100

width: 1024
height: 768

camera:
  position: [50, 15, 280.6]
  direction: [0, 0.15, -1]
  length: 140
  fov: 0.5135

air_absorption: [0, 0, 0]

grid: [2, 2]

spheres:
  - name: "left"
    radius: 100000
    center: [100001, 40.8, 81.6]
    emission: [0,0,0]
    color: [0.623, 0.521, 0.438]
    reflection: "diffuse"
    transmission: "none"

  - name: "right"
    radius: 100000
    center: [-99901, 40.8, 81.6]
    emission: [0,0,0]
    color: [0.572, 0.616, 1.035]
    reflection: "diffuse"
    transmission: "none"

  - name: "back"
    radius: 100000
    center: [50, 40.8, 100000]
    emission: [0,0,0]
    color: [0.543, 0.571, 0.622]
    reflection: "diffuse"
    transmission: "none"

  - name: "front"
    radius: 100000
    center: [50, 40.8, -99830]
    emission: [0,0,0]
    color: [0.543, 0.571, 0.622]
    reflection: "diffuse"
    transmission: "none"

  - name: "bottom"
    radius: 100000
    center: [50, 100000, 81.6]
    emission: [0,0,0]
    color: [0.543, 0.571, 0.622]
    reflection: "diffuse"
    transmission: "none"

  - name: "top"
    radius: 100000
    center: [50, -99918.4, 81.6]
    emission: [0,0,0]
    color: [0.543, 0.571, 0.622]
    reflection: "diffuse"
    transmission: "none"

  - name: "mirror"
    radius: 16.5
    center: [27, 16.5, 47]
    emission: [0,0,0]
    color: [1,1,1]
    reflection: "normal"
    transmission: "normal"
    refractive_index: -0.7

  - name: "glass"
    radius: 16.5
    center: [73, 16.5, 78]
    emission: [0,0,0]
    color: [1,1,1]
    reflection: "normal"
    transmission: "normal"
    refractive_index: 1.3
    absorption: [0.002, 0.01, 0.003]

  - name: "light"
    radius: 600
    center: [50, 681.33, 81.6]
    emission: [4,4,4]
    color: [0,0,0]
    reflection: "diffuse"
    transmission: "none"

